on:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update
      - name: Build release binaries
        run: cargo build --release
      - name: Archive binaries
        run: tar -czvf linux-binaries.tar.gz -C ./target/release poster
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            linux-binaries.tar.gz
