on:
  release:
    types: [published]
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build release binaries
        run: cargo build --release
      - name: Archive binaries (Linux)
        if: runner.os == 'Linux'
        run: tar -czvf linux-binaries.tar.gz -C ./target/release poster
      - name: Archive binaries (Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path ./target/release/poster.exe -DestinationPath windows-binaries.zip
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            linux-binaries.tar.gz
            windows-binaries.zip
